name: 💡 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Keep this short and practical.

  - type: textarea
    id: request
    attributes:
      label: What feature do you want?
      description: Describe the requested behavior.
      placeholder: I'd like to...
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Why is this useful?
      description: Share a real use case.
      placeholder: This helps because...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered (optional)
      placeholder: Any workaround or alternative you already tried.

  - type: textarea
    id: additional
    attributes:
      label: Additional context (optional)
      placeholder: Links, mockups, screenshots, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I have searched existing issues and feature requests to make sure this isn't a duplicate
          required: true
